version: "3.0"

services:

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]

  kibana:
      container_name: kb-container
      image: docker.elastic.co/kibana/kibana:8.6.2
      environment:
        - ELASTICSEARCH_HOSTS=http://es-container:9200
      networks:
        - es-net
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601
  
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'trustpilot'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - es-net
    ports:
      - '3306:3306'
  
  scraping_trustpilot:
    container_name: scraping-container
    image: scraping_image:latest
    networks:
      - es-net
    volumes:
      - /usr/app/src
    depends_on:
      - mysql
      - elasticsearch

  api:
    container_name: api-container
    image: api_image:latest
    networks:
      - es-net
    volumes:
      - /usr/app/src
    depends_on:
      - scraping_trustpilot
    ports:
      - '8000:8000'
  
networks:
  es-net:

